version: 1

envfile: .env

before-all:
  quiet: true
  cmds:
    - echo "before all in root"
    - |
      echo "hello multi line"

      for i in {1..10}; do
        echo "lool $i"
      done
    - echo "MANO=cole" >> $ACT_ENV

acts:
  act0:
    cmds:
      - echo "hello act0"
      - echo "Rendered {{.MY_ENV_VAR}}"
      - grep -q MY_NAME $ACT_ENV_FILE || printf "MY_NAME=Shirley\n" >> $ACT_ENV_FILE
      - echo "MY_ENV_VAR=$MY_ENV_VAR"
      - echo "MY_NAME is $MY_NAME"

  act1:
    flags:
      - check:false
      - name
    cmds:
      - echo "root act 1"
      - echo "check=$FLAG_CHECK"
      - echo "name is $FLAG_NAME"
      - echo "other args are $@"

  act2:
    redirect: child/actfile.yml
  
  act3:
    acts:
      _:
        cmds: echo "default act3"
      act31:
        cmds: echo "hello act31"
      act32:
        include: child/actfile.yml
  
  act4:
    cmds:
      - act: act2
      - act: act1 -test


  error:
    cmds:
      - echo "hello"
      - exit 1

  child:
    include: child/actfile.yml
