name: release-binaries
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: make release folder
        run: mkdir -p .releases/linux-amd64
      - name: build
        run: GOOS=linux GOARCH=amd64 go build -o .releases/linux-amd64 github.com/nosebit/act
      - name: compress release folder
        run: tar czfv .release/linux-amd64.tar.gz .release/linux-amd64/
      - name: upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-amd64
          path: .releases/linux-amd64.tar.gz
